Bundle with 2.4.19 bundler version
Brakeman complained about the bundler version

ERROR:  Error installing bundler:
  	There are no versions of bundler (= 2.5.23) compatible with your Ruby & RubyGems
  	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.7.221.