fix undefined method `match?'
failing tests:
rails test test/models/project_group_test.rb:39
rails test test/models/project_media_5_test.rb:799
rails test test/controllers/graphql_controller_7_test.rb:370
rails test test/controllers/graphql_controller_5_test.rb:200

- we make sure original_claim is not nil before trying to match
- after that was fixed, project_media_5_test.rb:799 was still failing:
     - we werent passing team
     - so it failed to get the pender_key, since that expects a team
     - questions:
          - why was this working before? we expected team before as well
          - do we need to have team?