Update smooch-api to version that supports Ruby 3.0
We were receiving a NoMethodError: undefined method `encode' for URI:Module
from the Smooch API because their version of the gem that supports v1.1 of
the API (v4.0+) uses URI.encode, which has been removed.

I submitted an issue on the repo, but for now we need to fork and try a
new approach. This commit points to that experimental version of the gem.

CV2-3595