ArgumentError: After create callback :increment_project_association_annotations_count has not been defined
`skip_callback` on tests only works in the first call